config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  resources :tweets do
    member do
    get "preview"
    end

    collection do
      get 'search'
      end

    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    include PgSearch::Model
 pg_search_scope :search_full_text, against: {
    userName: 'A',
    id: 'B',
 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    Pagy::DEFAULT[:items] = 10
    Pagy::DEFAULT[:size]  = [1,4,4,1]
    require 'pagy/extras/bootstrap'
    require 'pagy/extras/overflow'
    Pagy::DEFAULT[:overflow] = :empty_page
    include Pagy::Backend  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
    if params[:query_text].present?
      @tweets = @tweets.search_full_text(params[:query_text])
      @pagy, @tweets = pagy(@tweets.search_full_text(params[:query_text]))
    else
      @pagy, @tweets = pagy(Tweet.all)
    end
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:description, :userName)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClonTwitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body>
    <div class = "container">
      <div class = "justify-content-center text-center">
        <%= yield %>
      </div>
    </div>
    <footer class="text-center pt-4 ">
      <div class="container-fluid">
        <p class="fot">© 2023 Leonel Clavijo .Todos los <br> derechos reservados.</p>
      </div>
    </footer>
    
    <!-- bootstrap js + popper -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
        integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
        integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ"
        crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "mb-3">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description,class:"form-control" %>
  </div>

  <div class = "mb-3">
    <%= form.label :userName, style: "display: block" %>
    <%= form.text_field :userName,class:"form-control" %>
  </div>

  <div class = "mb-3">
    <%= form.submit "Crear", class:"btn btn-dark" %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  
<table class="table table-dark table-striped">
      <thead>
          <tr>              
              <th>Username:</th>  
              <th>Description:</th>            
          </tr>
      </thead>
      <tbody>          
          <tr>
              <td><%= tweet.userName %></td>
              <td><%= tweet.description %></td>
          </tr>
      </tbody>
  </table>
</div>

app/views/tweets/edit.html.erb
<h1>Editar</h1>

<%= render "form", tweet: @tweet %>

<br>


  <div class="mb-3">
    <td><a class="btn btn-secondary" role="button"<%= link_to "Ver", @tweet %> </td> 
    <td><a class="btn btn-secondary" role="button"<%= link_to "Inicio", tweets_path %></td>
  </div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tweets</h1>

<div class="container-fluid">
  <div class="mb-3">  
    <%= form_with url: tweets_path, class:"d-flex", method: :get do |form| %>  
      <%= form.text_field :query_text, placeholder: "buscar", value: params[:query_text], class:"form-control me-2" %>
      <%= form.submit "buscar", class:"btn btn-secondary" %>
    <% end %>
  </div>
  <table class="table table-dark table-striped">
      <thead>
          <tr>
              <th>ID</th>
              <th>Usuario</th>
              <th>Tweet</th>            
              <th>Ver</th>
          </tr>
      </thead>
      <tbody>
          <% @tweets.each do |tweet| %>
          <tr>
              <td><%= tweet.id %></td>
              <td><%= tweet.userName %></td>
              <td><%= tweet.description %></td>
              
              <td><a class="btn btn-secondary" role="button" <%= link_to "Ver tweet", tweet %></td>
              
          </tr>
      
          <% end %>
      </tbody>
  </table>
  <a class="btn btn-dark" role="button" <%= link_to "NUEVO", new_tweet_path %>
  <div class="pag-bar">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/tweets/new.html.erb
<h1>Crear Tweets</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  
  <td><a class="btn btn-dark" role="button" <%= link_to "Inicio", tweets_path %></td>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>
<h1>Ver Tweets</h1>
<%= render @tweet %>

<div>  
  <div class="mb-3">
    <td><a class="btn btn-dark" role="button"<%= link_to "Eliminar", @tweet, method: :delete %></td>
  </div>
  <div class="mb-3">
    <td><a class="btn btn-secondary" role="button"<%= link_to "Editar", edit_tweet_path(@tweet) %> </td> 
    <td><a class="btn btn-secondary" role="button"<%= link_to "Inicio", tweets_path %></td>
  </div>
</div>